<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Flotilla</RootNamespace>
    <Version>0.1.0</Version>
    <Product>Flotilla</Product>
    <Description>Mod manager for UBOAT</Description>
    <ApplicationIcon>Flotilla.ico</ApplicationIcon>
  </PropertyGroup>

</Project>
